### ISSUE TITLE
The Japanese name of Zuran Orb 

### ISSUE THREAD

**Issue by ababaSigrun** [alecrem/middleschool-cardlist#3]
hello
I wasn't sure if I should say MTGJSON, so here

The Japanese name of Zuran Orb seems to be "ズアーの宝珠".

http://mtgwiki.com/wiki/%E3%82%BA%E3%82%A2%E3%83%BC%E3%81%AE%E5%AE%9D%E7%8F%A0/Zuran_Orb

**Comment by alecrem** [comment]
Thank you! This is very helpful.

I think Zuran Orb was first printed in Japanese in Modern Horizons 2, but I have only looked at the old border sets...

I need to check if there are later Japanese printings of the cards I don't have a Japanese name for.
